name: proyecto_final
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  riverpod: ^2.6.1
  sizer: ^3.0.5
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  carousel_slider: ^5.0.0
  cached_network_image: ^3.2.3
  latlong2: ^0.9.1
  flutter_map: ^6.1.0
  youtube_player_flutter: ^9.1.1
  geolocator: ^14.0.0
  image_picker: ^1.1.2
  permission_handler: ^12.0.0+1
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
